### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by kelokchan** [Flo0806/fs-imagesize#1]
First of all thanks for this awesome plugin! I notice there's a `console.log` within the library that is constantly showing up whenever react re-renders. Would be great if you could clean it up so I don't have to patch this package. Thanks!

**Comment by Flo0806** [comment]
Hello @kelokchan 
Thx for this report and many thx for using this little package!
I have removed the `console.log` and the updated version 0.1.2 is online on npm (and the changed code is online on GitHub, too).

Greetings, Flo
